### ISSUE TITLE
mxCalendar Repeating Weekly Problem

### ISSUE THREAD

**Issue by crimsonpixel** [CharlesMx/mxCalendar#144]
Hi there, I'm using Revo 2.2.11 with mxCalendar 1.1.10  and whilst I can create individual dates, I am unable to create repeating events. 

I did have a previous calendar running but removed that, cleared the cache and uninstalled everything. Re-installed latest version but still seem to be getting the problem. Also the google map doesn't work, although I believe there is a fix for that.

There are no errors in the log to suggest what the problem is, however every time I try to create a repeating event it ends up in Past Events.

I am happy to give you access to the deployment to see the problem.

**Comment by PatchRanger** [comment]
Looks related to #98 : not filling in the `Last Occurance` field (which represents `repeatenddate` from database) leads to missing that event from any views, either in `web` context, or `mgr`.

**Comment by PatchRanger** [comment]
I guess I've finally debugged it.
Context, calendar and category are all could be blank that makes them agnostic for particular parameter.
Meantime, we can filter both by blank context/calendar/category (ie not filtering by particular parameter) or by specific value.
Currently filter doesn't handle it right.
I am going to provide the pull-request for this issue.
