### ISSUE TITLE
Mgr browser console error "tinyMCE is not defined"

### ISSUE THREAD

**Issue by dashukin** [CharlesMx/mxCalendar#145]
MODX: 2.2.10-pl (traditional).
mxCalendar: 1.1.10-pl
file: 'assets/components/mxcalendars/js/mgr/widgets/mxcalendars.grid.js'
TinyMCE: 4.3.3-pl

An error occures right after quick update of calendar's item (when code is trying to run if-statement "if(tinyMCE)...").
But there's no tinyMCE global variable at that moment, so browser throws an error "Uncaught ReferenceError: tinyMCE is not defined".
Basically it doesn't prevent calendar's item data from updating, but brokes any other quick update option, preventing it's "quick update window" from closing. 
A quick fix is to use "window.tinyMCE" instead of "tinyMCE" global variable.

**Comment by Lefthandmedia** [comment]
I still get this error with MxCalendar 1.1.10... has the fix been released?
