### ISSUE TITLE
Display in MODX 2.3

### ISSUE THREAD

**Issue by crimsonpixel** [CharlesMx/mxCalendar#161]
The form for entering data on Repeating event when creating or editing an entry has become a bit jumbled in Revo 2.3.

![mxcalendar](https://cloud.githubusercontent.com/assets/2063237/3656541/a1a56e8a-1187-11e4-9a68-b422303a18db.png)

**Comment by pyrographics** [comment]
Any update on this issue?  It is causing problems with one of our sites.  I would apply the above but I don't want to break forms elsewhere in the manager.

**Comment by pyrographics** [comment]
Any update on this?

**Comment by Lefthandmedia** [comment]
my guess is that the project is abandoned

**Comment by Spheerys** [comment]
Thanks for the tip @mediengaarage !
A new release should be usefull @CharlesMx :)

**Comment by CharlesMx** [comment]
Appreciate all the patience and support on this extra. I'm getting back on the saddle to revive it. Will work to get updates out on progress.

**Comment by mediengaarage** [comment]
Great to hear Charles! I think mxCalendar is the best Calendar-Tool for ModX

**Comment by Spheerys** [comment]
Thanks Charles :)

**Comment by crimsonpixel** [comment]
Hey Charles that's great to hear - this is a great extra for MODX and it would be good to clear some of the issues and get it up to speed.  I am happy to make a donation towards your time as well if it helps as I appreciate the hours of work that must go into the coding.

**Comment by Lefthandmedia** [comment]
Great to hear you're back. I guess i was wrong ;)

**Comment by CharlesMx** [comment]
thank you all, I'm going to work on doing quick patching before tackling the bigger refactor efforts. hope to have a new release soon to at least get it functional asap.
