### ISSUE TITLE
Repeating Event Form Display is Wonky

### ISSUE THREAD

**Issue by skybluesofa** [CharlesMx/mxCalendar#171]
When I tick the 'Repeating Event' box, the fields that show are not displayed correctly; they overlap and are not clickable. Below is a screenshot.
![image](https://cloud.githubusercontent.com/assets/1657128/9769695/50a62316-56f1-11e5-8439-a31d396b27d9.png)

Any suggestions or workarounds?

**Comment by crimsonpixel** [comment]
See issue #161 for a work round with css.

**Comment by CharlesMx** [comment]
resolved in release 1.1.11-pl
