### ISSUE TITLE
Pop-up window width errors/lexicon adju

### ISSUE THREAD

**Issue by moniarde** [CharlesMx/mxCalendar#178]
I've found that all of the pop-up windows on mxCalendar 1.1.10-pl/MODx 2.4.2-pl that have been designated width:'auto' are being created massively wide (+5,000 px). Also, pop-u window title to create new calendars currently says 'Create New Category'.

Pull requests made to propose corrections to both.

**Comment by dimitrihilverda** [comment]
Could you give me the changes you made? I can't find it anywhere here.

**Comment by CharlesMx** [comment]
#184 
fix committed and ready for next release
