### ISSUE TITLE
Select language

### ISSUE THREAD

**Issue by Showa** [CharlesMx/mxCalendar#53]
Is it possible to put a select language option in the snippet properties?

I put this on line 1:
//verander de 'taal' van php
//standaard use php english but if your want you can edit it to any other language. More info can be found at http://www.php.net
setlocale(LC_TIME, 'NL_nl');

in the snippet it functioned but my calendar did start on jan 1 and didn't react anymore events gone etc, the list functioned normally. 

Maybe it should be in another place.

Regards Ad.

**Comment by kix23** [comment]
Still working on it?
Suggested fix wont work here :\ 
Wont work even if i change the Labels direcly in the default.inc.php in the "en" Directory.
Also wont change anything if i change values in modxManager language settings...
Really confused here!?

**Comment by kix23** [comment]
Still working on it?
Suggested fix wont work here :\ 
Wont even work if i change the Labels direcly in the default.inc.php in the "en" Directory.
Also wont change anything if i change values in modxManager language settings...
Really confused here!?
